### ISSUE TITLE
Error provisioning stack - ApiGatewayStage - stage already exists

### ISSUE THREAD

**Issue by jeffski** [svdgraaf/serverless-plugin-stage-variables#2]
I tried to set up the variables below:

```
custom:
  stageVariables:
    stage: ${opt:stage, self:provider.stage}
    service: ${self:service}

plugins:
  - serverless-plugin-stage-variables
```

But got the following error:

```
  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ApiGatewayStage
     - dev already exists.

  Stack Trace --------------------------------------------

ServerlessError: An error occurred while provisioning your stack: ApiGatewayStage - dev already exists.
    at sdk.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:91:33)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:509:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:566:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:611:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:690:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

Not sure if this is some kind of conflict with having stage set in the provider which looks like:

```
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2
  stage: dev
```

When I take out the plugin config everything deploys fine
