### ISSUE TITLE
Staging Variables not showing up, but are in the cloud-flare template?

### ISSUE THREAD

**Issue by Ryanb58** [svdgraaf/serverless-plugin-stage-variables#20]
I have things setup like so and am not getting any staging variables in my API Gateway.

```
service: groups

...

custom:
  stageVariables:
    thestage: iamavariable
  dotenv:
    path: /app/.env
  packageExternal:
    external:
      - '../lib'
  pythonRequirements:
    dockerizePip: false
  stage: ${opt:stage, self:provider.stage}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-plugin-stage-variables
  - serverless-package-external
```

And deploy with:
```
sls deploy -s beta
```

After the deploy, I am not seeing my variable in the staging variables area on my API. This was working about a week ago, and I haven't changed anything in this codebase since. Did AWS change something?
